[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.5.0"
edition = "2024"
license = "Apache-2.0"
rust-version = "1.85"

[workspace.dependencies]
anyhow = "1"
assert_cmd = "2"
clap = { version = "4", features = ["derive"] }
config = { version = "0.15", default-features = false, features = ["toml", "json", "yaml"] }
globset = "0.4"
jiff = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
sha1 = "0.10"
tempfile = "3"
thiserror = "2"
toml = "0.9"
ureq = { version = "3", default-features = false, features = ["rustls", "json", "charset"] }
libc = "0.2"
