packages:
  - "packages/*"

autoInstallPeers: true
saveExact: true
strictPeerDependencies: true
allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
  sharp: true
  tsdown: true
  unrs-resolver: true
