// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(intl_ai_uniffiFFI)
import intl_ai_uniffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_intl_ai_uniffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_intl_ai_uniffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureIntlAiUniffiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * A resolved intl-ai configuration plus the methods that run against it.
 * Construct once per project; the object is immutable and safe to share
 * across threads (UniFFI wraps it in an `Arc`).
 */
public protocol IntlAiProtocol: AnyObject, Sendable {
    
    /**
     * Report missing/stale/modified/unreviewed findings without writing.
     * Same behavior as `intl-ai check`; blocking.
     */
    func check(options: CheckOptions) throws  -> CheckReport
    
    /**
     * Same run as `check`, returning the exact JSON the CLI emits with
     * `--format json`.
     */
    func checkJson(options: CheckOptions) throws  -> String
    
    /**
     * Translate missing (or scoped stale/regenerated) keys into target
     * locale files. Same behavior as `intl-ai fill`; blocking.
     */
    func fill(options: FillOptions) throws  -> FillReport
    
    /**
     * Same run as `fill`, returning the exact JSON the CLI emits with
     * `--format json`.
     */
    func fillJson(options: FillOptions) throws  -> String
    
    /**
     * Absolute path of the resolved locale directory.
     */
    func localeDir()  -> String
    
    /**
     * Configured source locale.
     */
    func sourceLocale()  -> String
    
    /**
     * Per-locale inventory counts (same as `intl-ai status`). Read-only:
     * no configured checks run and no transport is resolved. `locales`
     * empty = config targets.
     */
    func status(locales: [String]) throws  -> [LocaleStatus]
    
    /**
     * Same run as `status`, returning `{"locales": [...]}` like
     * `intl-ai status --format json`.
     */
    func statusJson(locales: [String]) throws  -> String
    
    /**
     * Configured target locales.
     */
    func targetLocales()  -> [String]
    
}
/**
 * A resolved intl-ai configuration plus the methods that run against it.
 * Construct once per project; the object is immutable and safe to share
 * across threads (UniFFI wraps it in an `Arc`).
 */
open class IntlAi: IntlAiProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_intl_ai_uniffi_fn_clone_intlai(self.handle, $0) }
    }
    /**
     * Load `intl-ai.{toml,json,yaml}` from `config_path`, or discover it
     * under `working_dir` when `config_path` is `None`. `working_dir`
     * defaults to the process working directory; relative paths inside
     * the config resolve against the config file's directory.
     */
public convenience init(configPath: String?, workingDir: String?)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeIntlAiError_lift) {
        uniffiCallStatus in
    uniffi_intl_ai_uniffi_fn_constructor_intlai_new(
        FfiConverterOptionString.lower(configPath),
        FfiConverterOptionString.lower(workingDir),uniffiCallStatus
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_intl_ai_uniffi_fn_free_intlai(handle, $0) }
    }

    
    /**
     * Parse an inline config string instead of reading a file. Paths
     * inside it resolve against `working_dir` (default: process cwd).
     * `extends` is rejected for inline configs (see `config::load_from_str`).
     */
public static func fromConfigString(config: String, format: ConfigFormat, workingDir: String?)throws  -> IntlAi  {
    return try  FfiConverterTypeIntlAi_lift(try rustCallWithError(FfiConverterTypeIntlAiError_lift) {
        uniffiCallStatus in
    uniffi_intl_ai_uniffi_fn_constructor_intlai_from_config_string(
        FfiConverterString.lower(config),
        FfiConverterTypeConfigFormat_lower(format),
        FfiConverterOptionString.lower(workingDir),uniffiCallStatus
    )
})
}
    

    
    /**
     * Report missing/stale/modified/unreviewed findings without writing.
     * Same behavior as `intl-ai check`; blocking.
     */
open func check(options: CheckOptions)throws  -> CheckReport  {
    return try  FfiConverterTypeCheckReport_lift(try rustCallWithError(FfiConverterTypeIntlAiError_lift) {
        uniffiCallStatus in
    uniffi_intl_ai_uniffi_fn_method_intlai_check(
            self.uniffiCloneHandle(),
        FfiConverterTypeCheckOptions_lower(options),uniffiCallStatus
    )
})
}
    
    /**
     * Same run as `check`, returning the exact JSON the CLI emits with
     * `--format json`.
     */
open func checkJson(options: CheckOptions)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeIntlAiError_lift) {
        uniffiCallStatus in
    uniffi_intl_ai_uniffi_fn_method_intlai_check_json(
            self.uniffiCloneHandle(),
        FfiConverterTypeCheckOptions_lower(options),uniffiCallStatus
    )
})
}
    
    /**
     * Translate missing (or scoped stale/regenerated) keys into target
     * locale files. Same behavior as `intl-ai fill`; blocking.
     */
open func fill(options: FillOptions)throws  -> FillReport  {
    return try  FfiConverterTypeFillReport_lift(try rustCallWithError(FfiConverterTypeIntlAiError_lift) {
        uniffiCallStatus in
    uniffi_intl_ai_uniffi_fn_method_intlai_fill(
            self.uniffiCloneHandle(),
        FfiConverterTypeFillOptions_lower(options),uniffiCallStatus
    )
})
}
    
    /**
     * Same run as `fill`, returning the exact JSON the CLI emits with
     * `--format json`.
     */
open func fillJson(options: FillOptions)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeIntlAiError_lift) {
        uniffiCallStatus in
    uniffi_intl_ai_uniffi_fn_method_intlai_fill_json(
            self.uniffiCloneHandle(),
        FfiConverterTypeFillOptions_lower(options),uniffiCallStatus
    )
})
}
    
    /**
     * Absolute path of the resolved locale directory.
     */
open func localeDir() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_intl_ai_uniffi_fn_method_intlai_locale_dir(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Configured source locale.
     */
open func sourceLocale() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_intl_ai_uniffi_fn_method_intlai_source_locale(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Per-locale inventory counts (same as `intl-ai status`). Read-only:
     * no configured checks run and no transport is resolved. `locales`
     * empty = config targets.
     */
open func status(locales: [String])throws  -> [LocaleStatus]  {
    return try  FfiConverterSequenceTypeLocaleStatus.lift(try rustCallWithError(FfiConverterTypeIntlAiError_lift) {
        uniffiCallStatus in
    uniffi_intl_ai_uniffi_fn_method_intlai_status(
            self.uniffiCloneHandle(),
        FfiConverterSequenceString.lower(locales),uniffiCallStatus
    )
})
}
    
    /**
     * Same run as `status`, returning `{"locales": [...]}` like
     * `intl-ai status --format json`.
     */
open func statusJson(locales: [String])throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeIntlAiError_lift) {
        uniffiCallStatus in
    uniffi_intl_ai_uniffi_fn_method_intlai_status_json(
            self.uniffiCloneHandle(),
        FfiConverterSequenceString.lower(locales),uniffiCallStatus
    )
})
}
    
    /**
     * Configured target locales.
     */
open func targetLocales() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_intl_ai_uniffi_fn_method_intlai_target_locales(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIntlAi: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = IntlAi

    public static func lift(_ handle: UInt64) throws -> IntlAi {
        return IntlAi(unsafeFromHandle: handle)
    }

    public static func lower(_ value: IntlAi) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IntlAi {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: IntlAi, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIntlAi_lift(_ handle: UInt64) throws -> IntlAi {
    return try FfiConverterTypeIntlAi.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIntlAi_lower(_ value: IntlAi) -> UInt64 {
    return FfiConverterTypeIntlAi.lower(value)
}




/**
 * One rule-level violation reported by a configured check.
 */
public struct CheckFinding: Equatable, Hashable {
    public var key: String
    /**
     * Check id that produced the violation (`icu`, spec id, exec name).
     */
    public var check: String
    public var message: String
    /**
     * Replayed from the incremental check cache, not re-run this time.
     */
    public var cached: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(key: String, 
        /**
         * Check id that produced the violation (`icu`, spec id, exec name).
         */check: String, message: String, 
        /**
         * Replayed from the incremental check cache, not re-run this time.
         */cached: Bool) {
        self.key = key
        self.check = check
        self.message = message
        self.cached = cached
    }

    

    
}

#if compiler(>=6)
extension CheckFinding: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCheckFinding: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CheckFinding {
        return
            try CheckFinding(
                key: FfiConverterString.read(from: &buf), 
                check: FfiConverterString.read(from: &buf), 
                message: FfiConverterString.read(from: &buf), 
                cached: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: CheckFinding, into buf: inout [UInt8]) {
        FfiConverterString.write(value.key, into: &buf)
        FfiConverterString.write(value.check, into: &buf)
        FfiConverterString.write(value.message, into: &buf)
        FfiConverterBool.write(value.cached, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCheckFinding_lift(_ buf: RustBuffer) throws -> CheckFinding {
    return try FfiConverterTypeCheckFinding.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCheckFinding_lower(_ value: CheckFinding) -> RustBuffer {
    return FfiConverterTypeCheckFinding.lower(value)
}


/**
 * Options for `IntlAi.check` (mirrors `intl-ai check` flags).
 */
public struct CheckOptions: Equatable, Hashable {
    /**
     * Target locales; empty = config targets.
     */
    public var locales: [String]
    /**
     * Key glob specs; empty = all keys.
     */
    public var keys: [String]
    /**
     * File with one key glob per line; relative paths resolve against
     * the config directory. Merged with `keys`.
     */
    public var keysFile: String?
    /**
     * Scope stale/modified/unreviewed/invalid to one effective origin.
     */
    public var origin: OriginFilter?
    /**
     * Finding kinds that set `has_issues`. `None` = config
     * `check.fail_on`; `Some(empty)` clears the gate.
     */
    public var failOn: [FindingKind]?
    /**
     * Skip the stat-cache read/write for this run.
     */
    public var noCache: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Target locales; empty = config targets.
         */locales: [String], 
        /**
         * Key glob specs; empty = all keys.
         */keys: [String], 
        /**
         * File with one key glob per line; relative paths resolve against
         * the config directory. Merged with `keys`.
         */keysFile: String?, 
        /**
         * Scope stale/modified/unreviewed/invalid to one effective origin.
         */origin: OriginFilter?, 
        /**
         * Finding kinds that set `has_issues`. `None` = config
         * `check.fail_on`; `Some(empty)` clears the gate.
         */failOn: [FindingKind]?, 
        /**
         * Skip the stat-cache read/write for this run.
         */noCache: Bool) {
        self.locales = locales
        self.keys = keys
        self.keysFile = keysFile
        self.origin = origin
        self.failOn = failOn
        self.noCache = noCache
    }

    

    
}

#if compiler(>=6)
extension CheckOptions: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCheckOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CheckOptions {
        return
            try CheckOptions(
                locales: FfiConverterSequenceString.read(from: &buf), 
                keys: FfiConverterSequenceString.read(from: &buf), 
                keysFile: FfiConverterOptionString.read(from: &buf), 
                origin: FfiConverterOptionTypeOriginFilter.read(from: &buf), 
                failOn: FfiConverterOptionSequenceTypeFindingKind.read(from: &buf), 
                noCache: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: CheckOptions, into buf: inout [UInt8]) {
        FfiConverterSequenceString.write(value.locales, into: &buf)
        FfiConverterSequenceString.write(value.keys, into: &buf)
        FfiConverterOptionString.write(value.keysFile, into: &buf)
        FfiConverterOptionTypeOriginFilter.write(value.origin, into: &buf)
        FfiConverterOptionSequenceTypeFindingKind.write(value.failOn, into: &buf)
        FfiConverterBool.write(value.noCache, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCheckOptions_lift(_ buf: RustBuffer) throws -> CheckOptions {
    return try FfiConverterTypeCheckOptions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCheckOptions_lower(_ value: CheckOptions) -> RustBuffer {
    return FfiConverterTypeCheckOptions.lower(value)
}


/**
 * Result of `IntlAi.check`.
 */
public struct CheckReport: Equatable, Hashable {
    public var locales: [String: LocaleDiff]
    /**
     * Check-level failures (spec load, exec spawn, provider error).
     */
    public var errors: [String]
    /**
     * A `fail_on` kind or a check-level error fired.
     */
    public var hasIssues: Bool
    /**
     * Any finding at all, independent of `fail_on`.
     */
    public var hasFindings: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(locales: [String: LocaleDiff], 
        /**
         * Check-level failures (spec load, exec spawn, provider error).
         */errors: [String], 
        /**
         * A `fail_on` kind or a check-level error fired.
         */hasIssues: Bool, 
        /**
         * Any finding at all, independent of `fail_on`.
         */hasFindings: Bool) {
        self.locales = locales
        self.errors = errors
        self.hasIssues = hasIssues
        self.hasFindings = hasFindings
    }

    

    
}

#if compiler(>=6)
extension CheckReport: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCheckReport: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CheckReport {
        return
            try CheckReport(
                locales: FfiConverterDictionaryStringTypeLocaleDiff.read(from: &buf), 
                errors: FfiConverterSequenceString.read(from: &buf), 
                hasIssues: FfiConverterBool.read(from: &buf), 
                hasFindings: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: CheckReport, into buf: inout [UInt8]) {
        FfiConverterDictionaryStringTypeLocaleDiff.write(value.locales, into: &buf)
        FfiConverterSequenceString.write(value.errors, into: &buf)
        FfiConverterBool.write(value.hasIssues, into: &buf)
        FfiConverterBool.write(value.hasFindings, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCheckReport_lift(_ buf: RustBuffer) throws -> CheckReport {
    return try FfiConverterTypeCheckReport.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCheckReport_lower(_ value: CheckReport) -> RustBuffer {
    return FfiConverterTypeCheckReport.lower(value)
}


/**
 * A fill-time failure; `key` is `None` for locale-level failures.
 */
public struct FillFailure: Equatable, Hashable {
    public var locale: String
    public var key: String?
    public var kind: ErrorKind
    public var message: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(locale: String, key: String?, kind: ErrorKind, message: String) {
        self.locale = locale
        self.key = key
        self.kind = kind
        self.message = message
    }

    

    
}

#if compiler(>=6)
extension FillFailure: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFillFailure: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FillFailure {
        return
            try FillFailure(
                locale: FfiConverterString.read(from: &buf), 
                key: FfiConverterOptionString.read(from: &buf), 
                kind: FfiConverterTypeErrorKind.read(from: &buf), 
                message: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FillFailure, into buf: inout [UInt8]) {
        FfiConverterString.write(value.locale, into: &buf)
        FfiConverterOptionString.write(value.key, into: &buf)
        FfiConverterTypeErrorKind.write(value.kind, into: &buf)
        FfiConverterString.write(value.message, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFillFailure_lift(_ buf: RustBuffer) throws -> FillFailure {
    return try FfiConverterTypeFillFailure.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFillFailure_lower(_ value: FillFailure) -> RustBuffer {
    return FfiConverterTypeFillFailure.lower(value)
}


/**
 * Options for `IntlAi.fill` (mirrors `intl-ai fill` flags).
 */
public struct FillOptions: Equatable, Hashable {
    /**
     * Target locales; empty = config targets.
     */
    public var locales: [String]
    /**
     * Key glob specs (e.g. "auth.*"); empty = all keys.
     */
    public var keys: [String]
    /**
     * File with one key glob per line; relative paths resolve against
     * the config directory. Merged with `keys`.
     */
    public var keysFile: String?
    /**
     * Re-fill AI-owned keys whose source hash changed.
     */
    public var stale: Bool
    /**
     * Overwrite AI-owned existing values. Needs a `keys` scope or
     * `yes = true`.
     */
    public var regenerate: Bool
    /**
     * With `regenerate`: also overwrite human-owned values.
     */
    public var includeHuman: Bool
    /**
     * Compute and report without writing locale files or shards.
     */
    public var dryRun: Bool
    /**
     * Skip the stat-cache read/write for this run.
     */
    public var noCache: Bool
    /**
     * Validation-gate check names for this run (overrides the config
     * `fill.validate` list). Ignored when `no_validate` is set.
     */
    public var validate: [String]
    /**
     * Disable the configured `fill.validate` gate for this run.
     */
    public var noValidate: Bool
    /**
     * Override the threshold of any judge check in the gate (0..=1).
     */
    public var judgeThreshold: Double?
    /**
     * Confirm an unscoped `regenerate` (no key scope given).
     */
    public var yes: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Target locales; empty = config targets.
         */locales: [String], 
        /**
         * Key glob specs (e.g. "auth.*"); empty = all keys.
         */keys: [String], 
        /**
         * File with one key glob per line; relative paths resolve against
         * the config directory. Merged with `keys`.
         */keysFile: String?, 
        /**
         * Re-fill AI-owned keys whose source hash changed.
         */stale: Bool, 
        /**
         * Overwrite AI-owned existing values. Needs a `keys` scope or
         * `yes = true`.
         */regenerate: Bool, 
        /**
         * With `regenerate`: also overwrite human-owned values.
         */includeHuman: Bool, 
        /**
         * Compute and report without writing locale files or shards.
         */dryRun: Bool, 
        /**
         * Skip the stat-cache read/write for this run.
         */noCache: Bool, 
        /**
         * Validation-gate check names for this run (overrides the config
         * `fill.validate` list). Ignored when `no_validate` is set.
         */validate: [String], 
        /**
         * Disable the configured `fill.validate` gate for this run.
         */noValidate: Bool, 
        /**
         * Override the threshold of any judge check in the gate (0..=1).
         */judgeThreshold: Double?, 
        /**
         * Confirm an unscoped `regenerate` (no key scope given).
         */yes: Bool) {
        self.locales = locales
        self.keys = keys
        self.keysFile = keysFile
        self.stale = stale
        self.regenerate = regenerate
        self.includeHuman = includeHuman
        self.dryRun = dryRun
        self.noCache = noCache
        self.validate = validate
        self.noValidate = noValidate
        self.judgeThreshold = judgeThreshold
        self.yes = yes
    }

    

    
}

#if compiler(>=6)
extension FillOptions: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFillOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FillOptions {
        return
            try FillOptions(
                locales: FfiConverterSequenceString.read(from: &buf), 
                keys: FfiConverterSequenceString.read(from: &buf), 
                keysFile: FfiConverterOptionString.read(from: &buf), 
                stale: FfiConverterBool.read(from: &buf), 
                regenerate: FfiConverterBool.read(from: &buf), 
                includeHuman: FfiConverterBool.read(from: &buf), 
                dryRun: FfiConverterBool.read(from: &buf), 
                noCache: FfiConverterBool.read(from: &buf), 
                validate: FfiConverterSequenceString.read(from: &buf), 
                noValidate: FfiConverterBool.read(from: &buf), 
                judgeThreshold: FfiConverterOptionDouble.read(from: &buf), 
                yes: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FillOptions, into buf: inout [UInt8]) {
        FfiConverterSequenceString.write(value.locales, into: &buf)
        FfiConverterSequenceString.write(value.keys, into: &buf)
        FfiConverterOptionString.write(value.keysFile, into: &buf)
        FfiConverterBool.write(value.stale, into: &buf)
        FfiConverterBool.write(value.regenerate, into: &buf)
        FfiConverterBool.write(value.includeHuman, into: &buf)
        FfiConverterBool.write(value.dryRun, into: &buf)
        FfiConverterBool.write(value.noCache, into: &buf)
        FfiConverterSequenceString.write(value.validate, into: &buf)
        FfiConverterBool.write(value.noValidate, into: &buf)
        FfiConverterOptionDouble.write(value.judgeThreshold, into: &buf)
        FfiConverterBool.write(value.yes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFillOptions_lift(_ buf: RustBuffer) throws -> FillOptions {
    return try FfiConverterTypeFillOptions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFillOptions_lower(_ value: FillOptions) -> RustBuffer {
    return FfiConverterTypeFillOptions.lower(value)
}


/**
 * Result of `IntlAi.fill`.
 */
public struct FillReport: Equatable, Hashable {
    public var locales: [String: LocaleFillReport]
    /**
     * Per-key/per-locale failures; a failed batch marks every key in it.
     */
    public var failures: [FillFailure]
    public var dryRun: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(locales: [String: LocaleFillReport], 
        /**
         * Per-key/per-locale failures; a failed batch marks every key in it.
         */failures: [FillFailure], dryRun: Bool) {
        self.locales = locales
        self.failures = failures
        self.dryRun = dryRun
    }

    

    
}

#if compiler(>=6)
extension FillReport: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFillReport: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FillReport {
        return
            try FillReport(
                locales: FfiConverterDictionaryStringTypeLocaleFillReport.read(from: &buf), 
                failures: FfiConverterSequenceTypeFillFailure.read(from: &buf), 
                dryRun: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FillReport, into buf: inout [UInt8]) {
        FfiConverterDictionaryStringTypeLocaleFillReport.write(value.locales, into: &buf)
        FfiConverterSequenceTypeFillFailure.write(value.failures, into: &buf)
        FfiConverterBool.write(value.dryRun, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFillReport_lift(_ buf: RustBuffer) throws -> FillReport {
    return try FfiConverterTypeFillReport.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFillReport_lower(_ value: FillReport) -> RustBuffer {
    return FfiConverterTypeFillReport.lower(value)
}


/**
 * Per-locale structural diff plus rule violations.
 */
public struct LocaleDiff: Equatable, Hashable {
    public var missing: [String]
    public var stale: [String]
    public var modified: [String]
    public var extra: [String]
    public var unreviewed: [String]
    public var invalid: [CheckFinding]
    /**
     * Empty unless `[quality]` is configured.
     */
    public var quality: [String: QualityScore]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(missing: [String], stale: [String], modified: [String], extra: [String], unreviewed: [String], invalid: [CheckFinding], 
        /**
         * Empty unless `[quality]` is configured.
         */quality: [String: QualityScore]) {
        self.missing = missing
        self.stale = stale
        self.modified = modified
        self.extra = extra
        self.unreviewed = unreviewed
        self.invalid = invalid
        self.quality = quality
    }

    

    
}

#if compiler(>=6)
extension LocaleDiff: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLocaleDiff: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LocaleDiff {
        return
            try LocaleDiff(
                missing: FfiConverterSequenceString.read(from: &buf), 
                stale: FfiConverterSequenceString.read(from: &buf), 
                modified: FfiConverterSequenceString.read(from: &buf), 
                extra: FfiConverterSequenceString.read(from: &buf), 
                unreviewed: FfiConverterSequenceString.read(from: &buf), 
                invalid: FfiConverterSequenceTypeCheckFinding.read(from: &buf), 
                quality: FfiConverterDictionaryStringTypeQualityScore.read(from: &buf)
        )
    }

    public static func write(_ value: LocaleDiff, into buf: inout [UInt8]) {
        FfiConverterSequenceString.write(value.missing, into: &buf)
        FfiConverterSequenceString.write(value.stale, into: &buf)
        FfiConverterSequenceString.write(value.modified, into: &buf)
        FfiConverterSequenceString.write(value.extra, into: &buf)
        FfiConverterSequenceString.write(value.unreviewed, into: &buf)
        FfiConverterSequenceTypeCheckFinding.write(value.invalid, into: &buf)
        FfiConverterDictionaryStringTypeQualityScore.write(value.quality, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLocaleDiff_lift(_ buf: RustBuffer) throws -> LocaleDiff {
    return try FfiConverterTypeLocaleDiff.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLocaleDiff_lower(_ value: LocaleDiff) -> RustBuffer {
    return FfiConverterTypeLocaleDiff.lower(value)
}


/**
 * Per-locale outcome of `IntlAi.fill`.
 */
public struct LocaleFillReport: Equatable, Hashable {
    public var requested: UInt64
    /**
     * Provider answered for an in-chunk key.
     */
    public var translated: UInt64
    /**
     * Keys adopted into file + shard.
     */
    public var written: UInt64
    /**
     * Values regenerated that were human-owned (`include_human` tier).
     */
    public var regeneratedHuman: UInt64
    /**
     * Shard entries pruned (key gone from source and target).
     */
    public var pruned: UInt64
    public var adoptedHuman: UInt64
    public var reconciledHuman: UInt64
    /**
     * Scoped keys with an existing AI-owned value left alone.
     */
    public var skippedExisting: UInt64
    /**
     * Same set, human-owned subset.
     */
    public var skippedHuman: UInt64
    /**
     * In-chunk keys the provider omitted from its response.
     */
    public var omitted: [String]
    /**
     * Existing values destroyed by a write (leaf/shape replacement).
     */
    public var clobbered: [String]
    /**
     * Keys sent through a corrective round by the validation gate.
     */
    public var refilled: UInt64
    /**
     * Gate findings still open after the last corrective round; the
     * values were adopted anyway and live on the shard entry's
     * `quality.unresolved`.
     */
    public var unresolved: [CheckFinding]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(requested: UInt64, 
        /**
         * Provider answered for an in-chunk key.
         */translated: UInt64, 
        /**
         * Keys adopted into file + shard.
         */written: UInt64, 
        /**
         * Values regenerated that were human-owned (`include_human` tier).
         */regeneratedHuman: UInt64, 
        /**
         * Shard entries pruned (key gone from source and target).
         */pruned: UInt64, adoptedHuman: UInt64, reconciledHuman: UInt64, 
        /**
         * Scoped keys with an existing AI-owned value left alone.
         */skippedExisting: UInt64, 
        /**
         * Same set, human-owned subset.
         */skippedHuman: UInt64, 
        /**
         * In-chunk keys the provider omitted from its response.
         */omitted: [String], 
        /**
         * Existing values destroyed by a write (leaf/shape replacement).
         */clobbered: [String], 
        /**
         * Keys sent through a corrective round by the validation gate.
         */refilled: UInt64, 
        /**
         * Gate findings still open after the last corrective round; the
         * values were adopted anyway and live on the shard entry's
         * `quality.unresolved`.
         */unresolved: [CheckFinding]) {
        self.requested = requested
        self.translated = translated
        self.written = written
        self.regeneratedHuman = regeneratedHuman
        self.pruned = pruned
        self.adoptedHuman = adoptedHuman
        self.reconciledHuman = reconciledHuman
        self.skippedExisting = skippedExisting
        self.skippedHuman = skippedHuman
        self.omitted = omitted
        self.clobbered = clobbered
        self.refilled = refilled
        self.unresolved = unresolved
    }

    

    
}

#if compiler(>=6)
extension LocaleFillReport: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLocaleFillReport: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LocaleFillReport {
        return
            try LocaleFillReport(
                requested: FfiConverterUInt64.read(from: &buf), 
                translated: FfiConverterUInt64.read(from: &buf), 
                written: FfiConverterUInt64.read(from: &buf), 
                regeneratedHuman: FfiConverterUInt64.read(from: &buf), 
                pruned: FfiConverterUInt64.read(from: &buf), 
                adoptedHuman: FfiConverterUInt64.read(from: &buf), 
                reconciledHuman: FfiConverterUInt64.read(from: &buf), 
                skippedExisting: FfiConverterUInt64.read(from: &buf), 
                skippedHuman: FfiConverterUInt64.read(from: &buf), 
                omitted: FfiConverterSequenceString.read(from: &buf), 
                clobbered: FfiConverterSequenceString.read(from: &buf), 
                refilled: FfiConverterUInt64.read(from: &buf), 
                unresolved: FfiConverterSequenceTypeCheckFinding.read(from: &buf)
        )
    }

    public static func write(_ value: LocaleFillReport, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.requested, into: &buf)
        FfiConverterUInt64.write(value.translated, into: &buf)
        FfiConverterUInt64.write(value.written, into: &buf)
        FfiConverterUInt64.write(value.regeneratedHuman, into: &buf)
        FfiConverterUInt64.write(value.pruned, into: &buf)
        FfiConverterUInt64.write(value.adoptedHuman, into: &buf)
        FfiConverterUInt64.write(value.reconciledHuman, into: &buf)
        FfiConverterUInt64.write(value.skippedExisting, into: &buf)
        FfiConverterUInt64.write(value.skippedHuman, into: &buf)
        FfiConverterSequenceString.write(value.omitted, into: &buf)
        FfiConverterSequenceString.write(value.clobbered, into: &buf)
        FfiConverterUInt64.write(value.refilled, into: &buf)
        FfiConverterSequenceTypeCheckFinding.write(value.unresolved, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLocaleFillReport_lift(_ buf: RustBuffer) throws -> LocaleFillReport {
    return try FfiConverterTypeLocaleFillReport.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLocaleFillReport_lower(_ value: LocaleFillReport) -> RustBuffer {
    return FfiConverterTypeLocaleFillReport.lower(value)
}


/**
 * One locale's inventory for `IntlAi.status` (same counts as
 * `intl-ai status --format json`).
 */
public struct LocaleStatus: Equatable, Hashable {
    public var locale: String
    /**
     * Total lockfile shard entries.
     */
    public var entries: UInt64
    public var ai: UInt64
    public var human: UInt64
    public var reviewed: UInt64
    /**
     * Deliberately untranslated tombstones.
     */
    public var absent: UInt64
    public var missing: UInt64
    public var stale: UInt64
    public var modified: UInt64
    public var extra: UInt64
    public var unreviewed: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(locale: String, 
        /**
         * Total lockfile shard entries.
         */entries: UInt64, ai: UInt64, human: UInt64, reviewed: UInt64, 
        /**
         * Deliberately untranslated tombstones.
         */absent: UInt64, missing: UInt64, stale: UInt64, modified: UInt64, extra: UInt64, unreviewed: UInt64) {
        self.locale = locale
        self.entries = entries
        self.ai = ai
        self.human = human
        self.reviewed = reviewed
        self.absent = absent
        self.missing = missing
        self.stale = stale
        self.modified = modified
        self.extra = extra
        self.unreviewed = unreviewed
    }

    

    
}

#if compiler(>=6)
extension LocaleStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLocaleStatus: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LocaleStatus {
        return
            try LocaleStatus(
                locale: FfiConverterString.read(from: &buf), 
                entries: FfiConverterUInt64.read(from: &buf), 
                ai: FfiConverterUInt64.read(from: &buf), 
                human: FfiConverterUInt64.read(from: &buf), 
                reviewed: FfiConverterUInt64.read(from: &buf), 
                absent: FfiConverterUInt64.read(from: &buf), 
                missing: FfiConverterUInt64.read(from: &buf), 
                stale: FfiConverterUInt64.read(from: &buf), 
                modified: FfiConverterUInt64.read(from: &buf), 
                extra: FfiConverterUInt64.read(from: &buf), 
                unreviewed: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: LocaleStatus, into buf: inout [UInt8]) {
        FfiConverterString.write(value.locale, into: &buf)
        FfiConverterUInt64.write(value.entries, into: &buf)
        FfiConverterUInt64.write(value.ai, into: &buf)
        FfiConverterUInt64.write(value.human, into: &buf)
        FfiConverterUInt64.write(value.reviewed, into: &buf)
        FfiConverterUInt64.write(value.absent, into: &buf)
        FfiConverterUInt64.write(value.missing, into: &buf)
        FfiConverterUInt64.write(value.stale, into: &buf)
        FfiConverterUInt64.write(value.modified, into: &buf)
        FfiConverterUInt64.write(value.extra, into: &buf)
        FfiConverterUInt64.write(value.unreviewed, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLocaleStatus_lift(_ buf: RustBuffer) throws -> LocaleStatus {
    return try FfiConverterTypeLocaleStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLocaleStatus_lower(_ value: LocaleStatus) -> RustBuffer {
    return FfiConverterTypeLocaleStatus.lower(value)
}


/**
 * Per-key aggregate quality score when `[quality]` is configured.
 */
public struct QualityScore: Equatable, Hashable {
    public var score: Double
    public var band: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(score: Double, band: String) {
        self.score = score
        self.band = band
    }

    

    
}

#if compiler(>=6)
extension QualityScore: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeQualityScore: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> QualityScore {
        return
            try QualityScore(
                score: FfiConverterDouble.read(from: &buf), 
                band: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: QualityScore, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.score, into: &buf)
        FfiConverterString.write(value.band, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQualityScore_lift(_ buf: RustBuffer) throws -> QualityScore {
    return try FfiConverterTypeQualityScore.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQualityScore_lower(_ value: QualityScore) -> RustBuffer {
    return FfiConverterTypeQualityScore.lower(value)
}


/**
 * Format of an inline config string passed to `IntlAi::from_config_string`.
 */

public enum ConfigFormat: Equatable, Hashable {
    
    case toml
    case json
    case yaml





}

#if compiler(>=6)
extension ConfigFormat: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConfigFormat: FfiConverterRustBuffer {
    typealias SwiftType = ConfigFormat

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConfigFormat {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .toml
        
        case 2: return .json
        
        case 3: return .yaml
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ConfigFormat, into buf: inout [UInt8]) {
        switch value {
        
        
        case .toml:
            writeInt(&buf, Int32(1))
        
        
        case .json:
            writeInt(&buf, Int32(2))
        
        
        case .yaml:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConfigFormat_lift(_ buf: RustBuffer) throws -> ConfigFormat {
    return try FfiConverterTypeConfigFormat.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConfigFormat_lower(_ value: ConfigFormat) -> RustBuffer {
    return FfiConverterTypeConfigFormat.lower(value)
}



/**
 * Failure classification on `FillFailure.kind` (mirrors core `ErrorType`;
 * serializes snake_case like the CLI JSON).
 */

public enum ErrorKind: Equatable, Hashable {
    
    case rateLimit
    case http
    case spawnFailure
    case timeout
    case processExit
    case parseError
    case outputTruncated
    case validation
    case empty
    case config
    case lockfile
    case io
    case auth
    case unknown





}

#if compiler(>=6)
extension ErrorKind: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeErrorKind: FfiConverterRustBuffer {
    typealias SwiftType = ErrorKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ErrorKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .rateLimit
        
        case 2: return .http
        
        case 3: return .spawnFailure
        
        case 4: return .timeout
        
        case 5: return .processExit
        
        case 6: return .parseError
        
        case 7: return .outputTruncated
        
        case 8: return .validation
        
        case 9: return .empty
        
        case 10: return .config
        
        case 11: return .lockfile
        
        case 12: return .io
        
        case 13: return .auth
        
        case 14: return .unknown
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ErrorKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .rateLimit:
            writeInt(&buf, Int32(1))
        
        
        case .http:
            writeInt(&buf, Int32(2))
        
        
        case .spawnFailure:
            writeInt(&buf, Int32(3))
        
        
        case .timeout:
            writeInt(&buf, Int32(4))
        
        
        case .processExit:
            writeInt(&buf, Int32(5))
        
        
        case .parseError:
            writeInt(&buf, Int32(6))
        
        
        case .outputTruncated:
            writeInt(&buf, Int32(7))
        
        
        case .validation:
            writeInt(&buf, Int32(8))
        
        
        case .empty:
            writeInt(&buf, Int32(9))
        
        
        case .config:
            writeInt(&buf, Int32(10))
        
        
        case .lockfile:
            writeInt(&buf, Int32(11))
        
        
        case .io:
            writeInt(&buf, Int32(12))
        
        
        case .auth:
            writeInt(&buf, Int32(13))
        
        
        case .unknown:
            writeInt(&buf, Int32(14))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeErrorKind_lift(_ buf: RustBuffer) throws -> ErrorKind {
    return try FfiConverterTypeErrorKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeErrorKind_lower(_ value: ErrorKind) -> RustBuffer {
    return FfiConverterTypeErrorKind.lower(value)
}



/**
 * Finding bucket names (mirrors `check --fail-on` values).
 */

public enum FindingKind: Equatable, Hashable {
    
    case missing
    case stale
    case invalid
    case modified
    case extra
    case unreviewed





}

#if compiler(>=6)
extension FindingKind: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFindingKind: FfiConverterRustBuffer {
    typealias SwiftType = FindingKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FindingKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .missing
        
        case 2: return .stale
        
        case 3: return .invalid
        
        case 4: return .modified
        
        case 5: return .extra
        
        case 6: return .unreviewed
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FindingKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .missing:
            writeInt(&buf, Int32(1))
        
        
        case .stale:
            writeInt(&buf, Int32(2))
        
        
        case .invalid:
            writeInt(&buf, Int32(3))
        
        
        case .modified:
            writeInt(&buf, Int32(4))
        
        
        case .extra:
            writeInt(&buf, Int32(5))
        
        
        case .unreviewed:
            writeInt(&buf, Int32(6))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFindingKind_lift(_ buf: RustBuffer) throws -> FindingKind {
    return try FfiConverterTypeFindingKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFindingKind_lower(_ value: FindingKind) -> RustBuffer {
    return FfiConverterTypeFindingKind.lower(value)
}



/**
 * Error surface for the foreign bindings. Variants mirror the core
 * `Error` taxonomy so Swift/Kotlin catch clauses can branch on the same
 * buckets CLI consumers parse out of the JSON error envelope.
 */
public 
enum IntlAiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Config(String
    )
    case Lockfile(String
    )
    case Io(String
    )
    case Format(String
    )
    /**
     * Provider/transport failure; the string is prefixed with the core
     * `ErrorType` (snake_case) and the provider message.
     */
    case Transport(String
    )
    /**
     * Caller-side contract violation (e.g. unscoped regenerate without
     * `yes`, judge threshold outside 0..=1).
     */
    case Validation(String
    )
    case Other(String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension IntlAiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIntlAiError: FfiConverterRustBuffer {
    typealias SwiftType = IntlAiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IntlAiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Config(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .Lockfile(
            try FfiConverterString.read(from: &buf)
            )
        case 3: return .Io(
            try FfiConverterString.read(from: &buf)
            )
        case 4: return .Format(
            try FfiConverterString.read(from: &buf)
            )
        case 5: return .Transport(
            try FfiConverterString.read(from: &buf)
            )
        case 6: return .Validation(
            try FfiConverterString.read(from: &buf)
            )
        case 7: return .Other(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: IntlAiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Config(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Lockfile(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Io(v1):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Format(v1):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Transport(v1):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Validation(v1):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Other(v1):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIntlAiError_lift(_ buf: RustBuffer) throws -> IntlAiError {
    return try FfiConverterTypeIntlAiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIntlAiError_lower(_ value: IntlAiError) -> RustBuffer {
    return FfiConverterTypeIntlAiError.lower(value)
}


/**
 * Origin scope for `CheckOptions.origin` (mirrors `check --origin`).
 */

public enum OriginFilter: Equatable, Hashable {
    
    case ai
    case human





}

#if compiler(>=6)
extension OriginFilter: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOriginFilter: FfiConverterRustBuffer {
    typealias SwiftType = OriginFilter

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OriginFilter {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .ai
        
        case 2: return .human
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: OriginFilter, into buf: inout [UInt8]) {
        switch value {
        
        
        case .ai:
            writeInt(&buf, Int32(1))
        
        
        case .human:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOriginFilter_lift(_ buf: RustBuffer) throws -> OriginFilter {
    return try FfiConverterTypeOriginFilter.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOriginFilter_lower(_ value: OriginFilter) -> RustBuffer {
    return FfiConverterTypeOriginFilter.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeOriginFilter: FfiConverterRustBuffer {
    typealias SwiftType = OriginFilter?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeOriginFilter.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeOriginFilter.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceTypeFindingKind: FfiConverterRustBuffer {
    typealias SwiftType = [FindingKind]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceTypeFindingKind.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceTypeFindingKind.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCheckFinding: FfiConverterRustBuffer {
    typealias SwiftType = [CheckFinding]

    public static func write(_ value: [CheckFinding], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCheckFinding.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [CheckFinding] {
        let len: Int32 = try readInt(&buf)
        var seq = [CheckFinding]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCheckFinding.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFillFailure: FfiConverterRustBuffer {
    typealias SwiftType = [FillFailure]

    public static func write(_ value: [FillFailure], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFillFailure.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FillFailure] {
        let len: Int32 = try readInt(&buf)
        var seq = [FillFailure]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFillFailure.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeLocaleStatus: FfiConverterRustBuffer {
    typealias SwiftType = [LocaleStatus]

    public static func write(_ value: [LocaleStatus], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeLocaleStatus.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [LocaleStatus] {
        let len: Int32 = try readInt(&buf)
        var seq = [LocaleStatus]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeLocaleStatus.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFindingKind: FfiConverterRustBuffer {
    typealias SwiftType = [FindingKind]

    public static func write(_ value: [FindingKind], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFindingKind.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FindingKind] {
        let len: Int32 = try readInt(&buf)
        var seq = [FindingKind]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFindingKind.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringTypeLocaleDiff: FfiConverterRustBuffer {
    public static func write(_ value: [String: LocaleDiff], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterTypeLocaleDiff.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: LocaleDiff] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: LocaleDiff]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterTypeLocaleDiff.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringTypeLocaleFillReport: FfiConverterRustBuffer {
    public static func write(_ value: [String: LocaleFillReport], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterTypeLocaleFillReport.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: LocaleFillReport] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: LocaleFillReport]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterTypeLocaleFillReport.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringTypeQualityScore: FfiConverterRustBuffer {
    public static func write(_ value: [String: QualityScore], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterTypeQualityScore.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: QualityScore] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: QualityScore]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterTypeQualityScore.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_intl_ai_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_intl_ai_uniffi_checksum_method_intlai_check() != 35129) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_intl_ai_uniffi_checksum_method_intlai_check_json() != 2072) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_intl_ai_uniffi_checksum_method_intlai_fill() != 7109) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_intl_ai_uniffi_checksum_method_intlai_fill_json() != 17429) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_intl_ai_uniffi_checksum_method_intlai_locale_dir() != 15204) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_intl_ai_uniffi_checksum_method_intlai_source_locale() != 47488) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_intl_ai_uniffi_checksum_method_intlai_status() != 52225) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_intl_ai_uniffi_checksum_method_intlai_status_json() != 60277) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_intl_ai_uniffi_checksum_method_intlai_target_locales() != 50423) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_intl_ai_uniffi_checksum_constructor_intlai_from_config_string() != 29246) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_intl_ai_uniffi_checksum_constructor_intlai_new() != 31792) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureIntlAiUniffiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all